name: dala
region: nyc

# Databases (PostgreSQL and Redis)
databases:
  - name: dala-db
    engine: PG
    version: "15"
    size: basic-xs
    num_nodes: 1
    production: true
  - name: dala-redis
    engine: REDIS
    version: "7"
    size: basic-xs
    num_nodes: 1
    production: true

# Backend API Service
services:
  - name: backend
    github:
      repo: takudzwachitsungo/dala
      branch: main
      deploy_on_push: true
    source_dir: /backend
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    
    envs:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: ${dala-db.DATABASE_URL}
      - key: REDIS_URL
        value: ${dala-redis.DATABASE_URL}
      - key: JWT_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "43200"
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: CORS_ORIGINS
        value: ${APP_URL}
    
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    run_command: |
      alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000

# Frontend Static Site
static_sites:
  - name: frontend
    github:
      repo: takudzwachitsungo/dala
      branch: main
      deploy_on_push: true
    source_dir: /ui
    build_command: npm install && npm run build
    output_dir: /dist
    
    envs:
      - key: VITE_API_URL
        value: ${backend.PUBLIC_URL}/api/v1
    
    routes:
      - path: /
