"""Add safety_plan table (fixed)

Revision ID: 78d12f87d6d5
Revises: 01a186ae5ab9
Create Date: 2025-12-22 14:14:55.279739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78d12f87d6d5'
down_revision: Union[str, None] = '01a186ae5ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('warning_signs', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('internal_coping', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('social_contacts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('people_to_ask', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('professionals', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('emergency_contacts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('safe_environment', sa.Text(), nullable=True),
    sa.Column('reasons_to_live', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safety_plans')
    # ### end Alembic commands ###
